execute pathogen#infect()

set nocompatible
filetype plugin on

let mapleader = ","

syntax on
set background=dark
let g:solarized_termtrans=1
colorscheme solarized

" Mostrar siempre la linea de estado
set laststatus=2

" Al hacer scroll, mantener siempre lineas encima y debajo del cursor
set scrolloff=3

" Limitar el tamaño de la linea automáticamente
set textwidth=79

"
" Tabulaciones e identaciones
"

" Tamaño de la tabulación
set softtabstop=2
set shiftwidth=2
set tabstop=2

" Tabulaciones usando blancos
set expandtab

" Mostrar números de línea
set number

" Al insertar una linea, mantener la tabulacion
set autoindent

" Detectar tokens que inducen a modificar la tabulación (i.e. '{')
set smartindent

" Activar la regla
set ruler

"
" Búsquedas
"

" Resaltar resultados
set hlsearch

" Búsqueda incremental (busca según se escribe)
set incsearch

" Búsqueda case-insensitive
set ignorecase

" Ignora 'ignorecase' si hay mayúsculas en la cadena de búsqueda
set smartcase

autocmd Filetype mail setlocal spell
autocmd Filetype markdown setlocal spell

"
" Opciones dependientes de scripts/plugins
"

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_puppet_puppetlint_args  = '--no-documentation-check --no-autoloader_layout-check --no-class_inherits_from_params_class-check'

let g:airline#extensions#tabline#enabled = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline#extensions#tabline#left_sep = '▶'
let g:airline#extensions#tabline#right_sep = '◀'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '◀'
let g:airline_powerline_fonts = 1
