#!/bin/sh
# (let ((x-res-pixels 2560)
#       (y-res-pixels 1440)
#       (diagonal-inches 27))
#   (floor (/ (sqrt (+ (expt x-res-pixels 2) (expt y-res-pixels 2)))
#       diagonal-inches)))
#
# ;; 16:9 screen
# (let* ((x-res-pixels 2560)
#        (y-res-pixels 1440)
#        (phy-diag-inches 27)
#        (phy-x-inches (* phy-diag-inches 0.872))
#        (phy-y-inches (* phy-diag-inches 0.49))
#        (dpis (list
#               (/ x-res-pixels phy-x-inches)
#               (/ y-res-pixels phy-y-inches))))
#   (floor (/ (seq-reduce #'+ dpis 0) 2)))
xrandr --dpi 108
