# oama authorize microsoft your.address@cern.ch --device
# https://cern.service-now.com/service-portal?id=kb_article&n=KB0010811
encryption:
    tag: KEYRING

services:
    microsoft:
        client_id: 9e5f94bc-e8a4-4e73-b8be-63364c29d753
        auth_scope: https://outlook.office.com/IMAP.AccessAsUser.All
          https://outlook.office.com/SMTP.Send
          offline_access
